spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: sa
    password: ""

  jpa:
    show-sql: true

  config:
    import: classpath:access-config.yaml
